"""initial schema

Revision ID: 5788bf17b80a
Revises: 
Create Date: 2026-07-04 14:56:16.794866

"""
from alembic import op
import sqlalchemy as sa


revision = '5788bf17b80a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required_keys', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sources_key'), 'search_sources', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_keyword', sa.String(length=255), nullable=False),
    sa.Column('intent_target', sa.Enum('BUYERS', 'SELLERS', 'BOTH', name='intenttarget', native_enum=False, length=16), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('min_confidence', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_is_deleted'), 'campaigns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_campaigns_product_keyword'), 'campaigns', ['product_keyword'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('masked_value', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key_name', name='uq_integration_user_key')
    )
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('price_value', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SAVED', 'CONTACTED', 'REJECTED', name='leadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'source_key', 'external_id', name='uq_lead_campaign_source_external')
    )
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leads_location'), 'leads', ['location'], unique=False)
    op.create_index(op.f('ix_leads_posted_at'), 'leads', ['posted_at'], unique=False)
    op.create_index(op.f('ix_leads_product'), 'leads', ['product'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_source_key'), 'leads', ['source_key'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_jobs_campaign_id'), 'scraping_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_scraping_jobs_status'), 'scraping_jobs', ['status'], unique=False)
    op.create_table('lead_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('BUY', 'SELL', 'MENTION', 'SPAM', name='intentlabel', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('rule_signals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_classifications_intent'), 'lead_classifications', ['intent'], unique=False)
    op.create_index(op.f('ix_lead_classifications_lead_id'), 'lead_classifications', ['lead_id'], unique=True)
    # ### end Alembic commands ###

    # Postgres full-text search index for the leads list `q` filter
    # (SQLite test runs fall back to ILIKE, so this is dialect-guarded).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """CREATE INDEX ix_leads_fts ON leads
               USING gin (to_tsvector('english', coalesce(title, '') || ' ' || content))"""
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_leads_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_classifications_lead_id'), table_name='lead_classifications')
    op.drop_index(op.f('ix_lead_classifications_intent'), table_name='lead_classifications')
    op.drop_table('lead_classifications')
    op.drop_index(op.f('ix_scraping_jobs_status'), table_name='scraping_jobs')
    op.drop_index(op.f('ix_scraping_jobs_campaign_id'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_key'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_product'), table_name='leads')
    op.drop_index(op.f('ix_leads_posted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_location'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_product_keyword'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_deleted'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_sources_key'), table_name='search_sources')
    op.drop_table('search_sources')
    # ### end Alembic commands ###
